<?php namespace ProcessWire;

/**
 * Class for Editing URLs
 */
class WireInputHelper extends WireData implements Module {
/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return array
	 */
	public static function getModuleInfo() {
		return [
			'title' => 'WireInput Helper',
			'version' => 101,
			'summary' => 'adds Hooks to WireInput',
			'singular' => true,
			'autoload' => true,
		];
	}

    public function init() {
		$this->addHook('WireInput::generateUrl', function($event) {
			$input = $event->object;
			$event->return = $this->generateUrl($input, $event->arguments(0));
		});
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	protected function paginateUrlPath(WireInput $input, $pagenbr = 1) {
		$url = $input->url();
		$page = $this->wire('page');

		if (strpos($url, 'page') !== false) {
			$regex = "((page)\d{1,3})";
			$replace = ($pagenbr > 1) ? "page".$pagenbr : "";
			$url = preg_replace($regex, $replace, $url);
		} else {
			if (count($input->urlSegments())) {
				$last = count($input->urlSegments());
				$insertafter = '/'.$input->urlSegment($last).'/';
			} else {
				$insertafter = "/$page->name/";
			}
			$regex = "(($insertafter))";
			$replace = ($pagenbr > 1) ? $insertafter."page".$pagenbr."/" : $insertafter;
			$url = preg_replace($regex, $replace, $url);
		}
		return $url;
	}
    protected function generateUrl(WireInput $input, $options = []) {
        $defaults = [
			'includeQueryString'    => true,
			'removeFromQueryString' => [],
			'addToQueryString'      => [],
			'pagenbr'               => 1,
		];
        $options = array_merge($defaults, $options);
		$urlPath = $this->paginateUrlPath($input, $options['pagenbr']);

        if ($options['includeQueryString'] === false) {
            return $urlPath;
        }
        $get = new WireInputData();
		$get->setArray($input->get->getArray());

        foreach ($options['removeFromQueryString'] as $key) {
            $get->remove($key);
        }
        foreach ($options['addToQueryString'] as $key => $value) {
            $get->$key = $value;
        }
        if ($get->count() == 0) {
            return $urlPath;
        }
        return $urlPath . "?" . $get->queryString();
    }
}