<?php namespace ProcessWire;

/**
 * DplusRequest
 *
 * Class for Sending HTTP Requests to COBOL or to SELF
 */
class DplusRequest extends WireData implements Module {
	const DIR_FILES = '/usr/capsys/webserv/';
	const CGI = 'SFWEBSERVICE';
	const CGI_TEST = 'SFWEBSERVICETEST';

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Requests',
			'version' => 101,
			'summary' => 'Module for Sending Requests to Cobol, and to self',
			'singular' => true,
			'autoload' => true,
		);
	}

	/**
	 * Sends HTTP GET Request to CGI BIN file
	 * @param  string $sessionID SessionID for CGI Request
	 * @return bool
	 */
	public function cgi_request($sessionID) {
		$cgi = $this->wire('user')->use_production() ? self::CGI : self::CGI_TEST;
		$http = new WireHttp();
		$response = $http->get("127.0.0.1/cgi-bin/$cgi?fname=$sessionID");
		return $response !== false;
	}

	/**
	 * Writes an array one datem per line into the dplus directory
	 * @param  array  $data      Array of Lines for the request
	 * @param  string $filename  What to name File
	 * @return void
	 */
	function write_dplusfile($data, $filename) {
		$success = false;
		$file = '';
		foreach ($data as $line) {
			$file .= $line . "\n";
		}
		$filepath = self::DIR_FILES . $filename;
		$handle = fopen($filepath, "w") or die("cant open file");
		$success = fwrite($handle, $file);
		fclose($handle);
		return boolval($success);
	}
}
